### ISSUE TITLE
Too light in light mode ?

### ISSUE THREAD

**Issue by bepolymathe** [blueteafrog/logseq-gunmetal-theme#1]
Hi ! 

Thank you very much for this theme which I find very interesting in "dark" and which allows to have a more important writing width. 

However, the links are not colored on the "light" version. Is it desired?

![image](https://user-images.githubusercontent.com/29939805/150556918-7fb97d79-c1e6-4913-b799-94d63a78640a.png)

VERSUS

![image](https://user-images.githubusercontent.com/29939805/150556975-628215ad-e5a7-4b4e-82a1-4fa13cc8b45b.png)

**Comment by d5technews** [comment]
Hi, sorry I just saw this. Looks like the above might be from a different theme? Ref Links are colored in Gunmetal
![Screen Shot 2022-01-24 at 17 47 11](https://user-images.githubusercontent.com/7694090/150895590-fde63df5-86b7-4599-950b-b095840d2b8d.png)
![Screen Shot 2022-01-24 at 17 47 19](https://user-images.githubusercontent.com/7694090/150895593-3eb11db4-be81-4f96-b178-5efbbd7ccec0.png)
