### ISSUE TITLE
Code mirror title not visible

### ISSUE THREAD

**Issue by AvijeetPrasad** [blueteafrog/logseq-gunmetal-theme#2]
Hi,

In the light mode, the text in code title on the top right hand corner is not visible. Please see the attached screenshot.
![Screenshot 2022-01-29 at 12 01 35](https://user-images.githubusercontent.com/45669486/151658547-391de486-f808-446c-ada0-76c23fa56169.jpg)

**Comment by d5technews** [comment]
Hi,

This is the codemirror in light mode. Are you perhaps using the Gunmetal theme in conjunction with another theme? That could explain the conflicting styles.
<img width="1000" alt="Screen Shot 2022-01-29 at 16 52 28" src="https://user-images.githubusercontent.com/7694090/151682659-c5bdd3fc-f051-467a-9e96-f0be4c2ad505.png">

**Comment by AvijeetPrasad** [comment]
Hi, thanks for looking into it. I didn't realize that the codemirror text background was dark for light mode by design. I disabled my `custom.css` file that might have caused some conflicts, but another issue still remains. The text in the light mode code mirror appears like in low-resolution with a white shadow. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/45669486/151696834-c6005df9-5d3f-41e7-8b65-6b286f35aa35.jpeg)


I am also attaching a link to a  screen recording that highlights this issue and also shows my custom.css settings. We can see that this issue happens only with the light mode, the dark mode works as expected.

https://capture.dropbox.com/qUqfnSSDsvksyM9a

Also, sometimes, when I select the light mode, it shifts to the defaul theme which I am not sure why.

Let me know if you need any more info from my end.

**Comment by d5technews** [comment]
Thank you, for the feedback and for the screen capture. White text-shadow issue I was able to reproduce and will find a solution as soon as I investigate further. In reference to the theme selection reverting to default theme, from my understanding (I read this in the documentation, but unable to locate it for your reference) is a logseq feature that allows a user to `unselect` custom themes without having to search for and `select` (effectively deactivating the custom themes) the default theme.

**Comment by d5technews** [comment]
Created new issue for white text-shadow

**Comment by d5technews** [comment]
@AvijeetPrasad the white text shadow should be fixed now thank you for the feedback
