### ISSUE TITLE
Feature request: Light background for code mirror

### ISSUE THREAD

**Issue by AvijeetPrasad** [blueteafrog/logseq-gunmetal-theme#4]
Hi,

I really like your theme and have been using it both in light and dark mode. Thanks a lot for making this wonderful theme :) One issue that would really help me is, if we can have a lighter background for the code mirror as well. In the current version, I feel the code mirror is too dark and looks somewhat cut off from the rest of the page aesthetic. A light blue background (like the one that you use for block embeds) would probably be more desirable.

I am uploading a sample screenshot that illustrates this point.
![Screenshot 2022-04-21 at 15 12 15](https://user-images.githubusercontent.com/45669486/164465417-f747d7af-9c7e-416c-99c8-951ed89b42a7.jpg)

Thanks again!

**Comment by d5technews** [comment]
@AvijeetPrasad Thanks for using the theme and for your feedback. Sure, I'll look into over the weekend!

**Comment by d5technews** [comment]
@AvijeetPrasad I like your suggestions flows better with the light theme. Have a look please give me your opinion before I finalize the update. ![image](https://user-images.githubusercontent.com/7694090/165354414-e3dfb8f2-fe2b-4d75-9ae8-b796a3b81479.jpeg)

**Comment by AvijeetPrasad** [comment]
Hi! Thanks for the update. The code mirror looks great now :) 

I have a couple of related feedback/requests:
- In the current version (v 0.1.0), the selected text inside the code mirror wasn't properly highlighted. Maybe you can have a look at that as well.
- A minor request: for the code language background color, maybe something more subtle than orange can be used.

Thanks again for this very useful theme :)

**Comment by d5technews** [comment]
Thanks again for the feedback, are you referring to (see screenshots), as far as the code language background change, I'll need some time to look into it. Possibly over the weekend.
![Screen Shot 2022-04-27 at 3 41 12 PM](https://user-images.githubusercontent.com/7694090/165643571-06f4d3a0-bd46-4040-95fb-3e915043053e.jpg)
![Screen Shot 2022-04-27 at 3 43 18 PM](https://user-images.githubusercontent.com/7694090/165643574-4bc26ec0-9034-46f1-b69b-11bb69a0f89b.jpg)

**Comment by AvijeetPrasad** [comment]
Hi, thanks for the updates. Yes, I was referring to the selection highlighting in the code mirror as shown in your screenshots. Earlier, the contrast was a bit less. Now it looks great :) 

Thanks for looking into the code language background as well, but I would say that's a minor issue, and it would be already quite helpful if you can push the current updates :) Thanks again!

**Comment by d5technews** [comment]
@AvijeetPrasad should be finalized let me know if you experience any issues with the new update.

**Comment by AvijeetPrasad** [comment]
Looks great now 😀. Thanks a lot!
