### ISSUE TITLE
Offtopic question about Journal Pages

### ISSUE THREAD

**Issue by karkraeg** [blueteafrog/logseq-gunmetal-theme#5]
Hi, slightly offtopic: How do you get the calendar Icon before the date of your Journal pages like in the GIF you linked?: 
https://user-images.githubusercontent.com/7694090/147600668-9adfacca-1a56-4216-a4b2-65b159ad7351.mov

Thanks!

**Comment by d5technews** [comment]
Hi I use the following CSS to get the calendar emoji to show.  

```
.journal-title .title::before,
.is-journals .title::before {
	content: "📅";
	font-size: 0.75em;
	margin-right: 10px;
	vertical-align: text-bottom;
}

**Comment by karkraeg** [comment]
Thanks!
